import { NextResponse } from "next/server";

const products = [
  {
    id: "product-1",
    images: [
      "/images/products/Product.png",
      "/images/products/Product2.png",
      "/images/products/Product3.png",
    ],
    description: "Zandu Pure Honey, 500g & Kellogg's Oats, High in Protein and Fibre",
    details: "Zandu Pure Honey is sourced directly from the Himalayan forests. Combined with Kellogg's high-protein oats, this combo gives you the perfect energy-packed breakfast to kickstart your day.",
    rating: 4,
    discount: "$40",
    pricing: "200",
    stock: 120,
    sku: "ZND-HP-001",
  },
  {
    id: "product-2",
    images: [
      "/images/products/Product2.png",
      "/images/products/Product4.png",
      "/images/products/Product5.png",
    ],
    description: "Organic Raw Honey - Natural Sweetener & Healthy Oats Combo",
    details: "100% organic raw honey with no added sugar or preservatives. Paired with healthy rolled oats, this combo is perfect for weight management and a clean, natural diet.",
    rating: 3,
    discount: "$10",
    pricing: "120",
    stock: 85,
    sku: "ORG-RH-002",
  },
  {
    id: "product-3",
    images: [
      "/images/products/Product3.png",
      "/images/products/Product6.png",
      "/images/products/Product7.png",
    ],
    description: "Premium Quality Oats with Pure Himalayan Honey Pack",
    details: "Sourced from the pristine valleys of the Himalayas, this premium honey retains all natural enzymes and nutrients. Bundled with fine-quality oats for a wholesome meal.",
    rating: 2,
    discount: "$30",
    pricing: "110",
    stock: 60,
    sku: "PRM-HH-003",
  },
  {
    id: "product-4",
    images: [
      "/images/products/Product4.png",
      "/images/products/Product8.png",
      "/images/products/Product9.png",
    ],
    description: "Fitness Breakfast Kit: Multigrain Oats & Natural Honey",
    details: "Designed for fitness enthusiasts, this kit includes multigrain oats packed with fiber and natural honey that provides sustained energy without sugar spikes.",
    rating: 3,
    discount: "$50",
    pricing: "520",
    stock: 45,
    sku: "FIT-MG-004",
  },
  {
    id: "product-5",
    images: [
      "/images/products/Product5.png",
      "/images/products/Product10.png",
      "/images/products/Product11.png",
    ],
    description: "Healthy Morning Bundle - High Fibre Oats & Pure Honey",
    details: "Start your morning right with our high-fibre oats that support digestion and pure honey that boosts immunity. A simple, nutritious breakfast bundle for the whole family.",
    rating: 5,
    discount: "$30",
    pricing: "170",
    stock: 200,
    sku: "HMB-HF-005",
  },
];

const featuredProducts = [
  {
    id: "featured-1",
    images: [
      "/images/products/Product.png",
      "/images/products/Product11.png",
      "/images/products/Product10.png",
    ],
    description: "Zandu Pure Honey, 500g & Kellogg's Oats, High in Protein and Fibre",
    details: "Zandu Pure Honey is sourced directly from the Himalayan forests. Combined with Kellogg's high-protein oats, this combo gives you the perfect energy-packed breakfast to kickstart your day.",
    rating: 4,
    discount: "$40",
    pricing: "200",
    stock: 120,
    sku: "ZND-HP-001",
  },
  {
    id: "featured-2",
    images: [
      "/images/products/Product2.png",
      "/images/products/Product3.png",
      "/images/products/Product4.png",
    ],
    description: "Organic Raw Honey - Natural Sweetener & Healthy Oats Combo",
    details: "100% organic raw honey with no added sugar or preservatives. Paired with healthy rolled oats, this combo is perfect for weight management and a clean, natural diet.",
    rating: 3,
    discount: "$10",
    pricing: "120",
    stock: 85,
    sku: "ORG-RH-002",
  },
  {
    id: "featured-3",
    images: [
      "/images/products/Product3.png",
      "/images/products/Product5.png",
      "/images/products/Product6.png",
    ],
    description: "Premium Quality Oats with Pure Himalayan Honey Pack",
    details: "Sourced from the pristine valleys of the Himalayas, this premium honey retains all natural enzymes and nutrients. Bundled with fine-quality oats for a wholesome meal.",
    rating: 2,
    discount: "$30",
    pricing: "110",
    stock: 60,
    sku: "PRM-HH-003",
  },
  {
    id: "featured-4",
    images: [
      "/images/products/Product4.png",
      "/images/products/Product7.png",
      "/images/products/Product8.png",
    ],
    description: "Fitness Breakfast Kit: Multigrain Oats & Natural Honey",
    details: "Designed for fitness enthusiasts, this kit includes multigrain oats packed with fiber and natural honey that provides sustained energy without sugar spikes.",
    rating: 3,
    discount: "$50",
    pricing: "520",
    stock: 45,
    sku: "FIT-MG-004",
  },
  {
    id: "featured-5",
    images: [
      "/images/products/Product5.png",
      "/images/products/Product9.png",
      "/images/products/Product1.png",
    ],
    description: "Healthy Morning Bundle - High Fibre Oats & Pure Honey",
    details: "Start your morning right with our high-fibre oats that support digestion and pure honey that boosts immunity. A simple, nutritious breakfast bundle for the whole family.",
    rating: 5,
    discount: "$30",
    pricing: "170",
    stock: 200,
    sku: "HMB-HF-005",
  },
  {
    id: "featured-6",
    images: [
      "/images/products/Product6.png",
      "/images/products/Product10.png",
      "/images/products/Product11.png",
    ],
    description: "Pure Forest Honey & Rolled Oats Value Pack",
    details: "Wild forest honey collected from deep forests by expert beekeepers. Paired with classic rolled oats, this value pack offers great taste and nutrition at an affordable price.",
    rating: 4,
    discount: "$20",
    pricing: "250",
    stock: 95,
    sku: "FOR-RO-006",
  },
  {
    id: "featured-7",
    images: [
      "/images/products/Product7.png",
      "/images/products/Product12.png",
      "/images/products/Product13.png",
    ],
    description: "Quick Cooking Oats with Natural Sweet Honey",
    details: "Ready in just 3 minutes, these quick-cooking oats are perfect for busy mornings. Combined with naturally sweet honey, it's a fast and healthy meal with no compromise on taste.",
    rating: 4,
    discount: "$15",
    pricing: "180",
    stock: 150,
    sku: "QCK-NS-007",
  },
  {
    id: "featured-8",
    images: [
      "/images/products/Product8.png",
      "/images/products/Product1.png",
      "/images/products/Product2.png",
    ],
    description: "Diet Friendly Oats & Pure Organic Honey Combo",
    details: "Low-calorie, diet-friendly oats combined with pure organic honey make this the ideal combo for those on a health journey. Free from artificial flavors and preservatives.",
    rating: 5,
    discount: "$25",
    pricing: "310",
    stock: 75,
    sku: "DIT-PO-008",
  },
  {
    id: "featured-9",
    images: [
      "/images/products/Product9.png",
      "/images/products/Product3.png",
      "/images/products/Product4.png",
    ],
    description: "Standard Oats 1kg & Pure Honey 250g Pack",
    details: "A classic everyday combo — 1kg of standard rolled oats and 250g of pure honey. Great for daily breakfast routines and suitable for all age groups.",
    rating: 3,
    discount: "$12",
    pricing: "145",
    stock: 300,
    sku: "STD-PH-009",
  },
  {
    id: "featured-10",
    images: [
      "/images/products/Product10.png",
      "/images/products/Product5.png",
      "/images/products/Product6.png",
    ],
    description: "Nutritious Breakfast Mix - Honey and Oats Special",
    details: "A specially curated breakfast mix combining the goodness of honey and oats. Rich in antioxidants, natural sugars, and dietary fiber — ideal for a nutritious start to your day.",
    rating: 4,
    discount: "$18",
    pricing: "215",
    stock: 110,
    sku: "NTR-HO-010",
  },
  {
    id: "featured-11",
    images: [
      "/images/products/Product11.png",
      "/images/products/Product7.png",
      "/images/products/Product8.png",
    ],
    description: "Golden Honey & High Protein Oats Super Saver",
    details: "Our golden honey has a rich amber color and a deep floral taste. Paired with high-protein oats, this super saver pack is perfect for athletes and health-conscious individuals.",
    rating: 5,
    discount: "$35",
    pricing: "400",
    stock: 55,
    sku: "GLD-HP-011",
  },
  {
    id: "featured-12",
    images: [
      "/images/products/Product12.png",
      "/images/products/Product9.png",
      "/images/products/Product10.png",
    ],
    description: "Family Pack: Large Oats & Pure Wild Honey",
    details: "Our largest family pack — bulk oats and pure wild honey to keep the whole family nourished. Economical, healthy, and packed with natural goodness for weeks of breakfasts.",
    rating: 4,
    discount: "$45",
    pricing: "550",
    stock: 40,
    sku: "FAM-WH-012",
  },
  {
    id: "featured-13",
    images: [
      "/images/products/Product13.png",
      "/images/products/Product1.png",
      "/images/products/Product2.png",
    ],
    description: "Instant Oats & Pure Natural Honey Duo",
    details: "No cooking needed — just add hot water to these instant oats and drizzle with pure natural honey for a quick, delicious breakfast. Perfect for travel and busy lifestyles.",
    rating: 3,
    discount: "$08",
    pricing: "95",
    stock: 180,
    sku: "INS-NH-013",
  },
];

const categoryProducts = [
  {
    id: "cp-1",
    images: ["/images/products/Product.png", "/images/products/Product2.png", "/images/products/Product3.png"],
    description: "Buy 1Kg Lion Kashmir Honey & Get Kashmir Honey 500 Gm",
    details: "Premium Kashmir honey sourced from the lush valleys of Kashmir. This combo pack offers 1Kg of pure Lion Kashmir Honey along with a free 500g pack. Rich in natural enzymes and antioxidants.",
    rating: 5,
    ratingCount: 2,
    originalPrice: 30,
    pricing: 28,
    brand: "EcomZone",
    weights: ["500g", "1kg"],
    type: "add_to_cart",
    hasCountdown: true,
    countdownTarget: Date.now() + 307 * 24 * 60 * 60 * 1000,
    stock: 45,
    sku: "LKH-1KG-001",
  },
  {
    id: "cp-2",
    images: ["/images/products/Product3.png", "/images/products/Product4.png", "/images/products/Product5.png"],
    description: "Saffola Honey Active, Made With Sundarban Forest Honey",
    details: "Saffola Honey Active is made from the finest Sundarban forest honey. It undergoes a special NMR tested process to ensure purity. Great for daily consumption, cooking, and as a natural sweetener.",
    rating: 4,
    ratingCount: 3,
    priceMin: 22,
    priceMax: 28,
    pricing: 22,
    brand: "MegaMart",
    weights: ["500g", "750g"],
    type: "select_options",
    hasCountdown: false,
    stock: 120,
    sku: "SFA-SF-002",
  },
  {
    id: "cp-3",
    images: ["/images/products/Product5.png", "/images/products/Product6.png", "/images/products/Product7.png"],
    description: "Silicone Syrup Spoons Long Handle Mixing Spoon Honey",
    details: "High-quality silicone syrup spoons specially designed for honey and thick syrups. Long handle reaches deep into jars. Heat-resistant, non-stick, and easy to clean.",
    rating: 4,
    ratingCount: 1,
    pricing: 13,
    brand: "SmartShop",
    weights: ["500g"],
    type: "buy_product",
    hasCountdown: false,
    stock: 200,
    sku: "SLS-SP-003",
  },
  {
    id: "cp-4",
    images: ["/images/products/Product7.png", "/images/products/Product8.png", "/images/products/Product9.png"],
    description: "Vijaya Organic Natural, Wild, Forest And Multiflora Honey",
    details: "100% organic multiflora honey collected from wild forest flowers. Unprocessed and unfiltered to retain all natural goodness. Rich amber color with a deep, complex flavor profile.",
    rating: 3,
    ratingCount: 4,
    originalPrice: 30,
    pricing: 25,
    brand: "EcomZone",
    weights: ["500g", "750g", "1kg"],
    type: "add_to_cart",
    hasCountdown: false,
    stock: 78,
    sku: "VJO-MF-004",
  },
  {
    id: "cp-5",
    images: ["/images/products/Product9.png", "/images/products/Product10.png", "/images/products/Product11.png"],
    description: "World's No.1 Honey Brand With No Sugar Adulteration",
    details: "The world's most trusted honey brand, certified free from sugar adulteration. Triple-tested for purity using advanced NMR technology. Available in multiple sizes for every household.",
    rating: 5,
    ratingCount: 5,
    priceMin: 17,
    priceMax: 24,
    pricing: 17,
    brand: "MegaMart",
    weights: ["750g", "1kg", "2kg"],
    type: "select_options",
    hasCountdown: false,
    stock: 95,
    sku: "WNO-PH-005",
  },
  {
    id: "cp-6",
    images: ["/images/products/Product11.png", "/images/products/Product12.png", "/images/products/Product13.png"],
    description: "Pure Wild Forest Honey 500g — Cold Extracted & Unfiltered",
    details: "Cold-extracted wild forest honey that preserves all natural enzymes, vitamins, and minerals. Unfiltered for maximum health benefits. Perfect for immunity boosting and daily wellness.",
    rating: 4,
    ratingCount: 6,
    originalPrice: 22,
    pricing: 18,
    brand: "SmartShop",
    weights: ["500g", "750g"],
    type: "add_to_cart",
    hasCountdown: false,
    stock: 60,
    sku: "PWF-CE-006",
  },
];

const organicHoneyProducts = [
  {
    id: "organic-1",
    images: ["/images/products/Product.png", "/images/products/Product2.png", "/images/products/Product3.png"],
    description: "Pure Organic Kashmiri Honey - Raw & Unfiltered 500g",
    details: "Sourced from the pristine valleys of Kashmir, this organic honey is raw, unfiltered, and packed with natural enzymes.",
    rating: 5,
    ratingCount: 8,
    originalPrice: 35,
    pricing: 28,
    brand: "EcomZone",
    weights: ["500g", "1kg"],
    type: "add_to_cart",
    hasCountdown: true,
    countdownTarget: Date.now() + 120 * 24 * 60 * 60 * 1000,
    stock: 90,
    sku: "ORG-KH-001",
  },
  {
    id: "organic-2",
    images: ["/images/products/Product3.png", "/images/products/Product4.png", "/images/products/Product5.png"],
    description: "Organic Forest Honey with Natural Comb - Premium Pack",
    details: "Wild forest honey harvested with natural honeycomb. 100% organic, no artificial processing.",
    rating: 4,
    ratingCount: 5,
    priceMin: 22,
    priceMax: 30,
    pricing: 22,
    brand: "MegaMart",
    weights: ["500g", "750g"],
    type: "select_options",
    hasCountdown: false,
    stock: 65,
    sku: "ORG-FH-002",
  },
  {
    id: "organic-3",
    images: ["/images/products/Product5.png", "/images/products/Product6.png", "/images/products/Product7.png"],
    description: "Certified Organic Acacia Honey - Light & Floral 750g",
    details: "Delicate acacia honey with a light floral aroma. USDA certified organic. Perfect for tea and desserts.",
    rating: 4,
    ratingCount: 3,
    originalPrice: 28,
    pricing: 24,
    brand: "SmartShop",
    weights: ["500g", "750g"],
    type: "add_to_cart",
    hasCountdown: false,
    stock: 110,
    sku: "ORG-AH-003",
  },
  {
    id: "organic-4",
    images: ["/images/products/Product7.png", "/images/products/Product8.png", "/images/products/Product9.png"],
    description: "Organic Multiflora Honey - Farm Fresh & Unprocessed",
    details: "Collected from multiple organic flower sources. Rich in antioxidants and natural minerals.",
    rating: 5,
    ratingCount: 7,
    pricing: 19,
    brand: "EcomZone",
    weights: ["500g"],
    type: "add_to_cart",
    hasCountdown: true,
    countdownTarget: Date.now() + 200 * 24 * 60 * 60 * 1000,
    stock: 150,
    sku: "ORG-MH-004",
  },
  {
    id: "organic-5",
    images: ["/images/products/Product9.png", "/images/products/Product10.png", "/images/products/Product11.png"],
    description: "Premium Organic Jungali Honey - Wild Bee Harvest 1kg",
    details: "Rare wild bee honey from deep jungle regions. Thick, dark, and intensely flavored organic honey.",
    rating: 3,
    ratingCount: 4,
    priceMin: 30,
    priceMax: 40,
    pricing: 30,
    brand: "MegaMart",
    weights: ["750g", "1kg"],
    type: "select_options",
    hasCountdown: false,
    stock: 35,
    sku: "ORG-JH-005",
  },
  {
    id: "organic-6",
    images: ["/images/products/Product11.png", "/images/products/Product12.png", "/images/products/Product13.png"],
    description: "Organic Coriander Honey - Unique Flavor & Health Benefits",
    details: "Sourced from organic coriander flower fields. Known for its digestive benefits and unique taste profile.",
    rating: 4,
    ratingCount: 6,
    originalPrice: 25,
    pricing: 20,
    brand: "SmartShop",
    weights: ["500g", "750g"],
    type: "add_to_cart",
    hasCountdown: false,
    stock: 80,
    sku: "ORG-CH-006",
  },
];

const rawHoneyProducts = [
  {
    id: "raw-1",
    images: ["/images/products/Product2.png", "/images/products/Product3.png", "/images/products/Product4.png"],
    description: "Raw Unfiltered Honey - Cold Extracted Wildflower 500g",
    details: "Cold-extracted wildflower honey in its purest form. Never heated or filtered. Contains natural pollen and enzymes.",
    rating: 5,
    ratingCount: 10,
    originalPrice: 32,
    pricing: 26,
    brand: "EcomZone",
    weights: ["500g", "1kg"],
    type: "add_to_cart",
    hasCountdown: true,
    countdownTarget: Date.now() + 150 * 24 * 60 * 60 * 1000,
    stock: 70,
    sku: "RAW-WF-001",
  },
  {
    id: "raw-2",
    images: ["/images/products/Product4.png", "/images/products/Product5.png", "/images/products/Product6.png"],
    description: "Raw Monofloral Honey - Single Source Linden Blossom",
    details: "Premium monofloral honey from linden blossoms. Light golden color with a minty fresh aftertaste.",
    rating: 4,
    ratingCount: 6,
    priceMin: 18,
    priceMax: 26,
    pricing: 18,
    brand: "MegaMart",
    weights: ["500g", "750g"],
    type: "select_options",
    hasCountdown: false,
    stock: 95,
    sku: "RAW-LB-002",
  },
  {
    id: "raw-3",
    images: ["/images/products/Product6.png", "/images/products/Product7.png", "/images/products/Product8.png"],
    description: "Raw Black Honey - Dark & Rich Mineral Honey 750g",
    details: "Rare dark honey with exceptionally high mineral content. Bold, intense flavor perfect for health-conscious consumers.",
    rating: 5,
    ratingCount: 4,
    originalPrice: 40,
    pricing: 34,
    brand: "SmartShop",
    weights: ["500g", "750g", "1kg"],
    type: "add_to_cart",
    hasCountdown: false,
    stock: 40,
    sku: "RAW-BH-003",
  },
  {
    id: "raw-4",
    images: ["/images/products/Product8.png", "/images/products/Product9.png", "/images/products/Product10.png"],
    description: "Raw Multifloral Wild Honey - Forest Reserve Collection",
    details: "Harvested from protected forest reserves. A blend of multiple wildflower nectars creating complex flavors.",
    rating: 4,
    ratingCount: 8,
    pricing: 22,
    brand: "EcomZone",
    weights: ["500g", "1kg"],
    type: "add_to_cart",
    hasCountdown: true,
    countdownTarget: Date.now() + 180 * 24 * 60 * 60 * 1000,
    stock: 55,
    sku: "RAW-MF-004",
  },
  {
    id: "raw-5",
    images: ["/images/products/Product10.png", "/images/products/Product11.png", "/images/products/Product12.png"],
    description: "Raw Eucalyptus Honey - Medicinal Grade Immunity Booster",
    details: "Sourced from eucalyptus groves. Known for its throat-soothing and immunity-boosting medicinal properties.",
    rating: 3,
    ratingCount: 5,
    priceMin: 20,
    priceMax: 28,
    pricing: 20,
    brand: "MegaMart",
    weights: ["500g", "750g"],
    type: "select_options",
    hasCountdown: false,
    stock: 120,
    sku: "RAW-EH-005",
  },
  {
    id: "raw-6",
    images: ["/images/products/Product12.png", "/images/products/Product13.png", "/images/products/Product.png"],
    description: "Raw Wild Bee Honey - Unpasteurized & Enzyme Rich 1kg",
    details: "Completely raw and unpasteurized wild bee honey. Maximum enzyme activity for superior health benefits.",
    rating: 5,
    ratingCount: 9,
    originalPrice: 38,
    pricing: 30,
    brand: "SmartShop",
    weights: ["750g", "1kg"],
    type: "add_to_cart",
    hasCountdown: false,
    stock: 45,
    sku: "RAW-WB-006",
  },
];

const allProducts = [...products, ...featuredProducts, ...categoryProducts, ...organicHoneyProducts, ...rawHoneyProducts];

export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const id = searchParams.get("id");

  if (id) {
    const product = allProducts.find((p) => p.id === id);
    if (product) {
      // Pick 4 related products (excluding the current one)
      const related = allProducts
        .filter((p) => p.id !== id && p.images && p.pricing)
        .slice(0, 4);
      return NextResponse.json({ product, related });
    }
    return NextResponse.json({ error: "Product not found" }, { status: 404 });
  }

  return NextResponse.json({ products, featuredProducts, categoryProducts, organicHoneyProducts, rawHoneyProducts });
}
